- README.md
> Added name to contributor list

- README.md
Closes #12 because its Very Important Critical life goals
> Add Mike to contributors

- README.md
> Add name to contributors list

- README.md
> added name to contributors

- README.md
> add shachee to readme

- README.md
> Add Interns Header

- README.md
> Add Isabella

- README.md
> Add Ian to readme

- IntroToJavaWorkshop/src/section2/PentagonCrazy.java
> Changed the instruction of pentagon crazy to make it more clear

- Level1-Module2/src/_99_extra/PixelParty.java
Issue #89 - 
Image was not showing up in frame.
> Fix createLabel method

- Level3-Module2/.settings/org.eclipse.core.resources.prefs
- Level3-Module2/src/_99_extra/recursion_practice/Factorial.java
- Level3-Module2/src/_99_extra/recursion_practice/FibonacciSequence.java
- Level3-Module2/src/_99_extra/recursion_practice/IntroToRecursion.java
- Level3-Module2/src/_99_extra/recursion_practice/RecursionMath.java
- Level3-Module2/src/_99_extra/recursion_practice/StringTrimmer.java
> Add recursion recipies

- Level5-Module4/src/_00_Binary_Conversion/DecimalToBinary.java
The DecimalToBinary recipe was incomplete so I filled in the gaps.
> Update DecimalToBinary recipe

- Level0-Module4/src/_02_boolean/_1_sleepy_head/SleepyHead.java
Added more activities to practice using boolean variables.
Included ! modifier && and a while loop example.
> more boolean practice

- Level0-Module2/src/_01_random/_1_intro_to_random/IntroToRandom.java
- Level0-Module2/src/_01_random/_5_magic_8_ball/Magic8Ball.java
Changed intro to provide a "better" explanation of random bounds
Modified Magic 8 Ball to separate creation of Random object from number generation
> intro and Magic 8 Ball

- Level0-Module2/src/_03_string_conversion/_2_strings_cannot_add/StringsCannotAdd.java
- Level0-Module2/src/_03_string_conversion/_3_rollercoaster/RollerCoaster.java
Fixing the naming of packages in code.
> L0 bug/m2 package fix

- Level5-Module1/src/_06_Wait_and_Notify/Example/SynchedThreadPrinter.java
- Level5-Module1/src/_06_Wait_and_Notify/Example/ThreadPrinter.java
- Level5-Module1/src/_06_Wait_and_Notify/Example/WaitAndNotifyExample.java
- Level5-Module1/src/_06_Wait_and_Notify/Practice/SynchedSplitLoops.java
> added assignment to emphasize object.wait() and object.notify() for

- Level1-Module4/src/_02_simon_says/SimonSays.java
change from
// images.put(new Integer(KeyEvent.VK_UP), "up.jpg");
to
// images.put(KeyEvent.VK_UP, "up.jpg");
> Update SimonSays.java to remove "new Integer()" from hashmap put

- Level0-Module2/src/_02_methods/_3_dot_race/dot_race/dot_race.pde
- Level0-Module2/src/_02_methods/_4_moles_in_holes/moles_in_holes/moles_in_holes.pde
- Level0-Module2/src/_02_methods/_6_slippery_dot/slippery_dot/slippery_dot.pde
Introduction added to Processing recipes to describe goal of program for clarity
> L0 M2 clarify instructions

- Level0-Module0/README.md
- Level0-Module0/src/_02_code_flow/_1_robot_square/RobotSquare.java
- Level0-Module0/src/_02_code_flow/_2_robot_spiral/RobotSpiral.java
- Level0-Module0/src/_02_code_flow/_3_pentagon_crazy/PentagonCrazy.java
- Level0-Module0/src/_02_code_flow/_4_flaming_ninja_star/FlamingNinjaStar.java
- Level0-Module0/src/_04_amazing_games/_2_dragon_fight/DragonFight.java
- Level0-Module1/src/_05_for_loops/_1_my_ages/MyAges.java
Module 0 "Robot" recipes modified to use while loops. MyAges (Module 1) now has starter code and introduces students to for loops.
> L0 while loops first

- Level0-Module5/src/_02_nested_loops/_2_amazing_rings/amazing_rings/amazing_rings.pde
Many students (and some volunteers) need help with this recipe, so I broke it down into a few separate steps and included a couple of hints to make it more accessible to Level 0 students.
> Added steps to Amazing Rings

- Level0-Module5/src/_01_algorithms/_3_goofy_names/GoofyNames.java
This recipe used to use substring, which is not part of the Level0 skill set. Students have been taught charAt so this is now used to separate individual letters of the name for case change.
> Change GoofyNames to use charAt

- Level2-Module1/src/_00_intro_to_array_lists/ArrayListDemo.java
- Level2-Module1/src/_00_intro_to_array_lists/IntroToArrayLists.java
- Level2-Module1/src/_01_array_list_visualizer/VisualArrayLists.java
- Level2-Module1/src/_01_array_list_visualizer/data/Action.java
- Level2-Module1/src/_01_array_list_visualizer/data/ArrayList.java
- Level2-Module1/src/_01_array_list_visualizer/data/ArrayListDisplayPanel.java
- Level2-Module1/src/_02_array_list_guestbook/GuestBook.java
Extended the ArrayListDemo to include a few additional demos of ArrayList methods, and created a simple visualization of an ArrayList in the VisualArrayLists recipe.
> L2 m1 adding visual array lists

- LICENSE
https://creativecommons.org/licenses/by-sa/4.0/
You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
for any purpose, even commercially.
This license is acceptable for Free Cultural Works.
The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following terms:
Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
No additional restrictions — You may not …
> Add license for League Curriculum

- Level1-Module0/src/_04_drum_kit/DrumKit.java
Changed playSound() method to use Clip in place of deprecated AudioClip in DrumKit.
> L1 m0 audio clip replace

- Level0-Module1/src/_06_spot_the_error/Recipes.html
- Level0-Module2/src/_01_random/_1_intro_to_random/Recipe.html
- Level0-Module2/src/_01_random/_2_rock_paper_scissors/Recipe.html
- Level0-Module2/src/_01_random/_3_dice_roll/Recipe.html
- Level0-Module2/src/_01_random/_4_validation/Recipe.html
- Level0-Module2/src/_01_random/_5_magic_8_ball/Recipe.html
- Level0-Module2/src/_02_methods/_1_animal_farm/Recipe.html
- Level0-Module2/src/_02_methods/_2_safe_cracker/Recipe.html
- Level0-Module2/src/_03_string_conversion/_2_strings_cannot_add/Recipe.html
- Level0-Module2/src/_04_spot_the_error/Recipes.html
- Level0-Module3/src/_01_else_if/_1_robot_color_chooser/Recipe.html
- Level0-Module3/src/_01_else_if/_2_crazy_cat_lady/Recipe.html
- Level0-Module3/src/_01_else_if/_3_high_low/Recipe.html
- Level0-Module3/src/_02_loop_variables/_2_shiny_objects/Recipe.html
- Level0-Module3/src/_02_loop_variables/_3_robot_walk_of_fame/Recipe.html
- Level0-Module3/src/_02_loop_variables/_3_robot_walk_of_fame/WalkOfFame.java
- Level0-Module3/src/_03_modulo/_4_fizz_buzz/Recipe.html
- Level0-Module4/src/_01_double/_1_change_calculator/Recipe.html
- Level0-Module4/src/_02_boolean/_1_sleepy_head/Recipe.html
- Level0-Module4/src/_03_char/_2_string_methods/Recipe.html
- Level0-Module4/src/_03_char/_3_pi_aloud/Recipe.html
- Level0-Module5/src/_01_algorithms/_3_goofy_names/Recipe.html
- Level0-Module5/src/_03_method_writing/_2_happy_pet/Recipe.html
New recipe web pages have been added to curriculum. This pull request will add links to those web pages. 
THEREFORE THIS MUST NOT BE MERGED UNTIL AFTER CURRICULUM PULL REQUEST #92 HAS BEEN MERGED.
> L0 add links to web pages

- Level2-Module0/src/extra/MIDIKeyboard.java
Just a quick practice recipe that might be fun for students that have sound on their computer. It shows a simple KeyListener setup.
> L2M0 Extras - Added MIDIKeyboard recipe for KeyListener practice

- Level1-Module4/src/_03_jeopardy/Jeopardy.java
Added a few minor tweaks that I missed when updating the sound.
The file will be correctly opened in the same thread now and can be stopped from playing to keep with the instructions.
> L1M4-Jeopardy-Update

- Level1-Module2/bin/.gitignore
- Level1-Module3/src/_07_cow_timer/CowTimer.java
- Level1-Module3/src/_07_cow_timer/CowTimerRunner.java
Further removal of the deprecated JApplet
> L1M3 - Cow Timer Sound Update

- Level0-Module1/src/_04_int/_2_robot_in_space/RobotInSpace.java
Removing the deprecated JApplet used for sound and replacing it with AudioSystem
> L0M1 - Robot in Space - Update

- Level3-Module4/src/_02_IntroToQueues/_01_IntroToQueue.java
Quick fix just added a main method to this recipe because it doesn't have one. Unless it is intentionally not supposed to have one.
> Add main method to _01_IntroToQueue.java

- Level1-Module1/src/_05_vault/Vault.java
Since this is the first time the student will make a class that's not the Runner, the Vault class will now be given and the goal will be to create the SecretAgent class and a Runner
> L1M1 - Vault - Adding Vault

- Level1-Module3/src/_05_netflix/Movie.java
- Level1-Module3/src/_05_netflix/NetflixQueue.java
The instructions for this one seemed pretty clear so I'm just adding documentation and hopefully that'll clear up most of the confusion the students have
> L1M3 - NetflixQueue - Adding JavaDocs

- Level3-Module1/src/_06_Intro_To_Hash_Maps/_00_HashMapDemo.java
- Level3-Module1/src/_07_Meeting_Scheduler/MeetingSchedulerTest.java
- Level3-Module1/src/_07_Meeting_Scheduler/Schedule.java
- Level3-Module3/src/_00_Intro_To_String_Methods/_00_StringMethodsDemo.java
Meeting scheduler would pass if person2 (unchanged) was returned.
> Bug fix and improved demos

- Level0-Module0/src/_02_code_flow/_1_robot_square/RobotSquare.java
recommended use of setSpeed, move, and turn was confusing due to empty parenthesis
> add note of function arguments

- Level1-Module3/src/_02_static_smiley_blues/Smiley.java
> fix path typo

- Level5-Module0/src/_00_JButtons_with_Lambdas/IntroToLambdas.java
- Level5-Module0/src/_00_JButtons_with_Lambdas/LambdaButtons.java
- Level5-Module0/src/_00_JButtons_with_Lambdas/interfaces/AFunctionalInterface.java
- Level5-Module0/src/_00_JButtons_with_Lambdas/interfaces/NotAFunctionalInterface.java
An actual intro to lambda expressions
> L5M0 lambdas expressions: extra demo and instructions
